all_cities = [
    "Abidjan",
    "Abu Dhabi",
    "Abuja",
    "Acapulco",
    "Accra",
    "Addis Abeba",
    "Adelaide",
    "Algiers",
    "Amman",
    "Amsterdam",
    "Ankara",
    "Astana",
    "Asuncion",
    "Athens",
    "Atlanta",
    "Auckland",
    "Bahrain",
    "Baku",
    "Bangkok",
    "Barcelona",
    "Beijing",
    "Beirut",
    "Belfast",
    "Belgrade",
    "Berlin",
    "Bogotá",
    "Brasília",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Busan",
    "Cairns",
    "Cairo",
    "Canberra",
    "Cape Town",
    "Caracas",
    "Cartagena",
    "Cayenne",
    "Chicago",
    "Chongqing",
    "Colombo",
    "Copenhagen",
    "Córdoba",
    "Cozumel",
    "Dakar",
    "Dallas",
    "Damascus",
    "Darwin",
    "Dhaka",
    "Doha",
    "Dubai",
    "Dublin",
    "Frankfurt",
    "Geneva",
    "Glasgow",
    "Guadalajara",
    "Guatemala City",
    "Guayaquil",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Ho Chi Minh City",
    "Hong Kong",
    "Islamabad",
    "Istanbul",
    "Jakarta",
    "Jerusalem",
    "Johannesburg",
    "Kabul",
    "Kampala",
    "Karachi",
    "Kathmandu",
    "Kigali",
    "Kingston",
    "Kinshasa",
    "Kolkata",
    "Kuala Lumpur",
    "Kuwait City",
    "Kyiv",
    "La Paz",
    "Lagos",
    "Lima",
    "Lisbon",
    "London",
    "Los Angeles",
    "Madrid",
    "Managua",
    "Manila",
    "Melbourne",
    "Mexico City",
    "Miami",
    "Minsk",
    "Monterrey",
    "Montevideo",
    "Montreal",
    "Moscow",
    "Mumbai",
    "Munich",
    "Muscat",
    "Nairobi",
    "New Delhi",
    "New York",
    "Osaka",
    "Oslo",
    "Panama City",
    "Paris",
    "Perth",
    "Phnom Penh",
    "Porto Alegre",
    "Prague",
    "Quetta",
    "Quito",
    "Recife",
    "Rio de Janeiro",
    "Río Gallegos",
    "Riyadh",
    "Rome",
    "Saint Petersburg",
    "Salzburg",
    "San Francisco",
    "San José",
    "San Juan",
    "San Salvador",
    "Santiago",
    "Santo Domingo",
    "São Paulo",
    "Seoul",
    "Shanghai",
    "Shenyang",
    "Singapore",
    "Sofia",
    "Sydney",
    "Taipei",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Tel Aviv-Yafo",
    "Tokyo",
    "Toronto",
    "Tripoli",
    "Ulaanbaatar",
    "Vancouver",
    "Venice",
    "Vienna",
    "Warsaw",
    "Washington",
    "Wellington",
    "Yangon",
    "Zagreb",
    "Zurich",
]

extreme_longitude_cities_subset = [
    "Abidjan",
    "Accra",
    "Auckland",
    "Barcelona",
    "Brisbane",
    "London",
    "Los Angeles",
    "Madrid",
    "San Francisco",
    "Vancouver",
    "Wellington",
]
