all_cities = [
    "Dubai",
    "Abu Dhabi",
    "Kabul",
    "Buenos Aires",
    "Río Gallegos",
    "Córdoba",
    "Vienna",
    "Salzburg",
    "Perth",
    "Darwin",
    "Adelaide",
    "Sydney",
    "Melbourne",
    "Canberra",
    "Cairns",
    "Brisbane",
    "Baku",
    "Dhaka",
    "Brussels",
    "Sofia",
    "Bahrain",
    "La Paz",
    "Recife",
    "São Paulo",
    "Rio de Janeiro",
    "Porto Alegre",
    "Brasília",
    "Minsk",
    "Montreal",
    "Toronto",
    "Vancouver",
    "Kinshasa",
    "Zurich",
    "Geneva",
    "Abidjan",
    "Santiago",
    "Shanghai",
    "Chongqing",
    "Beijing",
    "Shenyang",
    "Cartagena",
    "Bogotá",
    "San José",
    "Havana",
    "Prague",
    "Munich",
    "Frankfurt",
    "Berlin",
    "Copenhagen",
    "Santo Domingo",
    "Algiers",
    "Quito",
    "Guayaquil",
    "Cairo",
    "Madrid",
    "Barcelona",
    "Addis Abeba",
    "Helsinki",
    "Paris",
    "London",
    "Glasgow",
    "Belfast",
    "Tbilisi",
    "Cayenne",
    "Accra",
    "Athens",
    "Guatemala City",
    "Hong Kong",
    "Tegucigalpa",
    "Zagreb",
    "Budapest",
    "Jakarta",
    "Dublin",
    "Jerusalem",
    "Tel Aviv-Yafo",
    "New Delhi",
    "Kolkata",
    "Mumbai",
    "Tehran",
    "Venice",
    "Rome",
    "Kingston",
    "Amman",
    "Tokyo",
    "Osaka",
    "Nairobi",
    "Phnom Penh",
    "Seoul",
    "Busan",
    "Kuwait City",
    "Astana",
    "Beirut",
    "Colombo",
    "Tripoli",
    "Yangon",
    "Ulaanbaatar",
    "Cozumel",
    "Mexico City",
    "Acapulco",
    "Monterrey",
    "Guadalajara",
    "Kuala Lumpur",
    "Lagos",
    "Abuja",
    "Managua",
    "Amsterdam",
    "Oslo",
    "Kathmandu",
    "Wellington",
    "Auckland",
    "Muscat",
    "Panama City",
    "Lima",
    "Manila",
    "Quetta",
    "Karachi",
    "Islamabad",
    "Warsaw",
    "San Juan",
    "Lisbon",
    "Asuncion",
    "Doha",
    "Bucharest",
    "Belgrade",
    "Saint Petersburg",
    "Moscow",
    "Kigali",
    "Riyadh",
    "Singapore",
    "Dakar",
    "San Salvador",
    "Damascus",
    "Bangkok",
    "Ankara",
    "Istanbul",
    "Taipei",
    "Kyiv",
    "Kampala",
    "Washington",
    "Miami",
    "Atlanta",
    "Dallas",
    "Chicago",
    "New York",
    "Los Angeles",
    "San Francisco",
    "Montevideo",
    "Caracas",
    "Ho Chi Minh City",
    "Hanoi",
    "Johannesburg",
    "Cape Town",
    "Harare",
]

extreme_longitude_cities_subset = [
    "Vancouver",
    "San Francisco",
    "Los Angeles",
    "Abidjan",
    "Madrid",
    "Accra",
    "London",
    "Barcelona",
    "Brisbane",
    "Auckland",
    "Wellington",
]
