name: vairify-nbk
channels:
  - conda-forge
  - defaults
dependencies:
  - black=24.4.2
  - cartopy=0.23.0
  - cfgrib=0.9.12.0
  - dask=2024.4.2
  - geopandas=0.14.4
  - jupyterlab=4.2.0
  - jupytext=1.16.2
  - netcdf4=1.6.5
  - pandas=2.2.2
  - pip=24.0
  - python=3.11.9
  - python-dotenv=1.0.1
  - requests=2.31.0
  - scipy=1.13.0
  - sqlite=3.45.3
  - xarray=2024.3.0
  - pip:
      - cads-api-client==1.0.2
      - cdsapi==0.7.0
      - tqdm==4.66.4