services:
  insitu-etl:
    image: ghcr.io/ecmwfcode4earth/vairify/vairify-insitu-etl
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - OPEN_AQ_API_KEY=${OPEN_AQ_API_KEY}
  forecast-etl:
    image: ghcr.io/ecmwfcode4earth/vairify/vairify-forecast-etl
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - CDSAPI_URL=${CDSAPI_URL}
      - CDSAPI_KEY=${CDSAPI_KEY}