FROM python:3.11

WORKDIR /app

COPY api/requirements.txt ./
RUN pip install -r requirements.txt

COPY api/src/ ./api/src
COPY shared/src ./shared/src
COPY logging.ini ./

ENV PYTHONPATH "${PYTHONPATH}:/app"

ENTRYPOINT ["fastapi", "run", "./api/src/main.py", "--root-path", "/api"]
