name: etl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bottleneck=1.3.8
  - cfgrib=0.9.11.0
  - dask=2024.4.2
  - netcdf4=1.6.5
  - pip
  - python=3.11.9
  - poetry=1.8
  - setuptools
  - xarray=2024.3.0
