services:
  db:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

  etl-insitu:
    image: ghcr.io/ecmwfcode4earth/vairify/vairify-etl-insitu
    container_name: etl-insitu
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - OPEN_AQ_API_URL=${OPEN_AQ_API_URL}
      - OPEN_AQ_API_KEY=${OPEN_AQ_API_KEY}
      - CDSAPI_URL=${CDSAPI_URL}
      - CDSAPI_KEY=${CDSAPI_KEY}
      - STORE_GRIB_FILES=${STORE_GRIB_FILES}
      
  etl-forecast:
    container_name: etl-forecast
    image: ghcr.io/ecmwfcode4earth/vairify/vairify-etl-forecast
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - CDSAPI_URL=${CDSAPI_URL}
      - CDSAPI_KEY=${CDSAPI_KEY}
      - STORE_GRIB_FILES=${STORE_GRIB_FILES}
    volumes:
      - data_textures:/app/data_textures

  api:
    container_name: backend-api
    image: ghcr.io/ecmwfcode4earth/vairify/vairify-backend-api
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=${MONGO_DB_NAME}

  ui:
    container_name: frontend-ui
    image: ghcr.io/ecmwfcode4earth/vairify/vairify-frontend
    depends_on:
      - api
    ports:
      - 8001:80
    volumes:
      - data_textures:/app/data_textures


volumes:
  database: {}
  data_textures: {}