apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: etl-insitu
  name: etl-insitu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etl-insitu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yaml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: etl-insitu
    spec:
      containers:
        - env:
            - name: CDSAPI_KEY
            - name: CDSAPI_URL
            - name: MONGO_DB_NAME
            - name: MONGO_DB_URI
              value: mongodb://mongo:27017/
            - name: OPEN_AQ_API_KEY
            - name: OPEN_AQ_API_URL
            - name: STORE_GRIB_FILES
          image: ghcr.io/ecmwfcode4earth/vairify/vairify-etl-insitu
          name: etl-insitu
      restartPolicy: Always
