apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: etl-forecast
  name: etl-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etl-forecast
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yaml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: etl-forecast
    spec:
      containers:
        - env:
            - name: CDSAPI_KEY
            - name: CDSAPI_URL
            - name: MONGO_DB_NAME
            - name: MONGO_DB_URI
              value: mongodb://mongo:27017/
            - name: STORE_GRIB_FILES
          image: ghcr.io/ecmwfcode4earth/vairify/vairify-etl-forecast
          name: etl-forecast
          volumeMounts:
            - mountPath: /app/data_textures
              name: data-textures
      restartPolicy: Always
      volumes:
        - name: data-textures
          persistentVolumeClaim:
            claimName: data-textures
