apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 80
  selector:
    io.kompose.service: ui
