name: Publish ETL docker image
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN}}
      - name: build
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/etl:latest --docker-file air-quality-backend/Dockerfile.cron
      - name: publish
        run: |
          docker push ${{ github.repository }}/etl:latest