name: Harbor insitu ETL docker image build and publish 

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: eccr.ecmwf.int
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./air-quality-backend
          file: ./air-quality-backend/Dockerfile.insitu
          platforms: linux/amd64
          push: true
          tags: "eccr.ecmwf.int/cams-applications/vairify-etl-insitu:latest" 