name: Build and publish insitu ETL docker images

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN}} ghcr.io
      - name: build
        run: |
          cd air-quality-backend
          docker build . -t ghcr.io/${{ github.repository }}/etl-insitu:latest -f Dockerfile.insitu.cron
      - name: publish
        run: |
          docker push ghcr.io/${{ github.repository }}/etl-insitu:latest