name: pr-build

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches:
      - 'main'

jobs:
  run-pr-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          environment-file: air-quality-backend/conda/etl.yml
          auto-activate-base: false
          activate-environment: etl
         
      - name: Run lint check
        run: python -m flake8 --append-config air-quality-backend/.flake8 air-quality-backend

      - name: Run unit tests
        run: python -m pytest --cov=src --cov=scripts --cov-report=xml:air-quality-backend/tests/coverage/test_report.xml air-quality-backend/tests
        
      - name: Code Coverage Report
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: air-quality-backend/tests/coverage/test_report.xml
            token: ${{ secrets.GITHUB_TOKEN }}
