name: pr-build

on:
  push:
    branches:
    - 'main'
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches:
    - 'main'
   

jobs:
  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          environment-file: air-quality-backend/conda/linting_environment.yml
          auto-activate-base: false
          activate-environment: linting-env
         
      - name: Run lint check
        run: python -m flake8 --append-config air-quality-backend/.flake8 air-quality-backend

