name: pr-build

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches:
      - 'main'

jobs:
  detect-change-scope:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: read
    outputs:
      etl: ${{ steps.filter.outputs.etl }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: dorny/paths-filter@v3.0.2  
        id: filter
        with:
          filters: |
            etl:
              - 'air-quality-backend/src/etl/**'
              - 'air-quality-backend/tests/etl_tests/**'
            api:
              - 'air-quality-backend/src/api/**'
              - 'air-quality-backend/tests/api_tests/**'
