name: pr-build

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches:
      - 'main'

jobs:
  detect-change-scope:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: read
    outputs:
      etl: ${{ steps.filter.outputs.etl }}
      api: ${{ steps.filter.outputs.api }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3.0.2  
      id: filter
      with:
        filters: |
          etl:
            - 'air-quality-backend/src/air_quality/etl/**'
            - 'air-quality-backend/tests/etl_tests/**'
          api:
            - 'air-quality-backend/src/air_quality/api/**'
            - 'air-quality-backend/tests/api_tests/**'

  pr-checks:
    needs: detect-change-scope
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          environment-file: air-quality-backend/conda/etl_environment.yml
          auto-activate-base: false
          activate-environment: pr-env

      - name: Get Dependencies
        run: poetry install
        working-directory: ./air-quality-backend
        
      - name: Run lint check
        run: python -m flake8 --append-config .flake8
        working-directory: ./air-quality-backend
        
      - name: Run etl unit tests
        run: python -m pytest --cov=src/air_quality/etl --cov=scripts --cov-append tests/etl_tests
        if: ${{ needs.detect-change-scope.outputs.etl == 'true' }}
        working-directory: ./air-quality-backend

      - name: Run api unit tests
        run: python -m pytest --cov=src/air_quality/api --cov-append tests/api_tests
        if: ${{ needs.detect-change-scope.outputs.api == 'true' }}
        working-directory: ./air-quality-backend

      - name: Convert to report 
        run: coverage xml
        working-directory: ./air-quality-backend

      - name: Code Coverage Report
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: ./air-quality-backend/coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
